
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '144A98D4276B1B742EDED472CB70D3FE'
    
_lr_action_items = {'$end':([0,2,3,4,5,7,8,10,11,13,14,15,],[-3,0,-3,-3,-9,-1,-5,-2,-6,-4,-8,-7,]),'LPAREN':([0,1,3,4,5,8,9,11,13,14,15,],[1,1,1,1,-9,-5,1,-6,-4,-8,-7,]),'OR':([4,5,13,],[9,12,-4,]),'RPAREN':([1,3,4,5,6,7,8,10,11,13,14,15,],[-3,-3,-3,-9,13,-1,-5,-2,-6,-4,-8,-7,]),'CHAR':([0,1,3,4,5,8,11,12,13,14,15,],[5,5,5,5,-9,-5,-6,15,-4,-8,-7,]),'TIMES':([3,4,5,8,11,13,14,15,],[8,11,-9,-5,-6,-4,-8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'group':([0,1,3,4,9,],[4,4,4,4,14,]),'regexp':([0,1,3,4,],[2,6,7,10,]),'chars':([0,1,3,4,],[3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> regexp","S'",1,None,None,None),
  ('regexp -> chars regexp','regexp',2,'p_regexp','regexp.py',27),
  ('regexp -> group regexp','regexp',2,'p_regexp','regexp.py',28),
  ('regexp -> <empty>','regexp',0,'p_regexp_empty','regexp.py',32),
  ('group -> LPAREN regexp RPAREN','group',3,'p_group','regexp.py',36),
  ('chars -> chars TIMES','chars',2,'p_chars_times','regexp.py',40),
  ('chars -> group TIMES','chars',2,'p_chars_times','regexp.py',41),
  ('chars -> CHAR OR CHAR','chars',3,'p_chars_or','regexp.py',45),
  ('chars -> group OR group','chars',3,'p_chars_or','regexp.py',46),
  ('chars -> CHAR','chars',1,'p_chars','regexp.py',50),
]
